language: ruby
cache: bundler
rvm:
  - 2.1.2

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database eat_cheap_test;' -U postgres
script:
  - bundle exec rake spec
