language: ruby
bundler_args: --without development --path=~/.bundle
env:
  - RAILS_ENV=test
before_script:
  - rake db:setup
  - rake db:migrate
script:
  - rspec spec
before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "echo '--colour' > ~/.rspec"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - rspec spec
  - rake test
cache: bundler
cache:
  directories:
    - vendor/bundle
