language: ruby
bundler_args: --without development --path=~/.bundle
env:
  - RAILS_ENV=test
before_script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate
script:
  - bundle exec rspec spec
  - bundle exec rake test
before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "echo '--colour' > ~/.rspec"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.sample.yml config/database.yml
script:
  - bundle exec rspec spec
  - bundle exec rake test
cache: bundler
cache:
  directories:
    - vendor/bundle
